# Generated by Django 4.1.4 on 2023-03-12 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('tg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('language_code', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientsBotUIState',
            fields=[
                ('tg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.tguser')),
                ('patient_info_flag', models.BooleanField(default=False)),
                ('appointment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('problem', models.CharField(blank=True, max_length=80, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('experience', models.CharField(blank=True, max_length=20, null=True)),
                ('last_button_pressed', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistBotUIState',
            fields=[
                ('tg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.tguser')),
                ('authorized', models.BooleanField(default=False)),
                ('last_button_pressed', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('time', models.DateField(blank=True, null=True)),
                ('appointment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('problem', models.CharField(blank=True, max_length=80, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('experience', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.tguser')),
                ('psychologist_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.tguser')),
            ],
        ),
    ]
