# Generated by Django 3.2.16 on 2022-12-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='approved_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved time'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='processed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processed time'),
        ),
    ]
