# Generated by Django 3.2.16 on 2022-12-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_admin', '0002_auto_20221214_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='assigned_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
