# Generated by Django 3.2.16 on 2022-12-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_admin', '0003_alter_patient_assigned_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=150, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_nickname',
            field=models.CharField(max_length=50, verbose_name='Telegram nickname'),
        ),
    ]
