# Generated by Django 3.2.16 on 2022-12-15 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_admin', '0004_auto_20221214_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.date(2022, 12, 15)),
        ),
    ]
