# Generated by Django 3.2.16 on 2023-01-26 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import web_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0004_alter_sessions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 26, 16, 30, 37, 616664, tzinfo=utc), null=True, validators=[web_admin.models.Sessions.validate_date_time]),
        ),
    ]
