# Generated by Django 3.2.16 on 2022-12-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_admin', '0008_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='2022-12-15'),
        ),
    ]
