# Generated by Django 3.2.16 on 2022-12-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_admin', '0009_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, verbose_name='Added by'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='time_table_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='psychologist', to='Web_admin.sessions', verbose_name='time_table_id'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='Web_admin.patient', verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='session_type',
            field=models.CharField(blank=True, choices=[('IND', 'Individual'), ('GRP', 'Group'), ('WEB', 'Webinar')], default='IND', max_length=3, null=True),
        ),
    ]
