# Generated by Django 3.2.16 on 2022-12-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_admin', '0010_auto_20221215_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='time_table_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psychologist', to='Web_admin.sessions', verbose_name='time_table_id'),
        ),
    ]
